version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - '3000:3000'
    environment:
     DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    env_file:
      - ./.env.local
    volumes:
      - ./api:/app
      - ./api:/node_modules
      - ./api:/dist
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./api/seedDatabase.sql:/seed.sql
    
volumes:
  postgres-data: